version: "3.9"

services:
#  server:
#    container_name: server
#    build:
#      context: ./server
#      dockerfile: ./Dockerfile.dev
#    ports:
#      - "4000:4000"
#    volumes:
#      - ./:/app
#      - server_modules:/app/node_modules
#    restart: 'unless-stopped'
#    links:
#      - mongo


  mongo:
    image: mongo:latest
    restart: 'unless-stopped'
    ports:
      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - db:/data/db

volumes:
  db:
