version: "3.9"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile.prod
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - server_modules:/app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  server_modules:
