version: '3.9'

services:
  api:
    image: node-starter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env.development.local
    environment:
      NODE_ENV: 'development'
      DB_HOST: 'mongo_db'
    ports:
      - '4000:4000'
    depends_on:
      - mongo_db

  mongo_db:
    container_name: db_container
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
