version: '3.9'

services:

  mongo_db:
    container_name: db_container
    image: mongo
    environment:
      - DB_HOST="localhost"
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
